language: node_js
node_js:
  - '0.11.13'
  - '0.11.14'
  - '0.11.15'
  - '0.12'
  - 'io.js'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-lark' ]; then cd .. && eval "mv $currentfolder generator-lark" && cd generator-lark; fi
